// Barrel for the UI foundation layer.
// Usage: import { StatTile, AnimatedNumber, useToast } from '../components/ui'

export { default as Button } from './Button'
export { default as Card } from './Card'
export { default as Badge } from './Badge'
export { default as Modal } from './Modal'
export { default as Input } from './Input'
export { default as Select } from './Select'

export { default as AnimatedNumber } from './AnimatedNumber'
export { default as Sparkline } from './Sparkline'
export { default as ProgressRing } from './ProgressRing'
export { default as ProgressBar } from './ProgressBar'
export { default as Skeleton, SkeletonText, SkeletonCard } from './Skeleton'
export { default as ToastProvider, useToast } from './Toast'
export type { ToastType, ToastOptions } from './Toast'
export { default as CommandPalette, useCommandPalette } from './CommandPalette'
export type { Command } from './CommandPalette'
export { default as Tooltip } from './Tooltip'
export { default as Tabs } from './Tabs'
export type { TabItem } from './Tabs'
export { default as StatTile } from './StatTile'
export { default as PageTransition } from './PageTransition'
export { default as EmptyState } from './EmptyState'
export { default as ConfirmDialog, useConfirm } from './ConfirmDialog'
export type { ConfirmOptions } from './ConfirmDialog'

export { default as useCountUp } from '../../hooks/useCountUp'
export { default as useSpotlight } from '../../hooks/useSpotlight'
export { default as useHotkeys } from '../../hooks/useHotkeys'
export { default as useInView } from '../../hooks/useInView'
